spring:
  application:
    name: one-text-code
  datasource:
    url: jdbc:mysql://localhost:3306/one_text_code
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8601
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bin.onetextcode.controller
