spring:
  application:
    name: one-text-code
  datasource:
    url: jdbc:mysql://localhost:3306/one_text_code
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 3
  session:
    redis:
    timeout: 2592000
  profiles:
    active: local
server:
  port: 8601
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bin.onetextcode.controller
